name: CI Configuration

on:
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Composer Install
        uses: php-actions/composer@v6
        with:
          php_version: "8.3"
          command: composer install

      - name: Run all tests
        uses: php-actions/composer@v6
        with:
          php_version: "8.3"
          command: composer run all
    
